import styled, { css } from "styled-components";

/*
Props:
    - classname: Auto generated by styled-components
    - iconName: A string
    - action?: Function / Function ref.
    - children?: Optional React children
    - small?: Is the icon small or not, boolean value.

Icon wrappes an <i> element responsible for showing the icon from CAPPUCCICONS.
*/
export const Icon = ({
    classname,
    iconName,
    action = undefined,
    children = null,
    small = false,
}) => {
    return (
        <IconStyle className={classname} onClick={action} isSmall={small}>
            {children}
            <i className={`cp cp-${iconName}`}></i>
        </IconStyle>
    );
};

/* 
isSmall is additional style only applicable is the component isSmall prop is true.
This could be done inline(*) in IconStyle as well but I personaly think this is cleaner
to read.

* Inline could be wither as ```font-size: ${props => props.isSmall ? '0.85rem' : '2.5rem'} 
or like it is now but with out calling isSmall from a independant variable but add the 
style modification with the same css helper that is used in current variable.
 */
const isSmall = css`
    max-width: 15px;
    margin: 0 0.5rem 0 0;
    display: inline-flex;

    i {
        font-size: 0.85rem;
    }
`;

const IconStyle = styled.div`
    margin: 1rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    font-family: "Open Sans Condensed";
    width: auto;

    i {
        font-size: 2.5rem;
        color: ${(props) => props.theme.toggler.font};
        margin-top: 0.5rem;
    }

    ${(props) => props.isSmall && isSmall}
`;
